/**
 * Problem:
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position. Find the letter that was added in t.
 * 
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 * 
 * @param {string} s The first string to analyze
 * @param {string} t The second string to analyze
 * @return {character} The character that was added in t
 */

var findTheDifference = function(s, t) {
  let sum1 = 0,
    sum2 = 0;

  /* Sum up the char code for the first string */
  for (let char of s) {
    sum1 += char.charCodeAt();
  }

  /* Sum up the char code for the second string */
  for (let char of t) {
    sum2 += char.charCodeAt();
  }

  // Return the character converted from the difference between the two sums
  return String.fromCharCode(sum2 - sum1);
};
